version: '3.8'

services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: anoop102910
      POSTGRES_PASSWORD: Sahib@123postgres
      POSTGRES_DB: socially
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  dev-obs:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

  dev-test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: anoop102910
      POSTGRES_PASSWORD: Sahib@123postgres
      POSTGRES_DB: socially
    ports:
      - "5434:5432"

  dev-test-obs:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data
    ports:
      - "9001:9000"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
